FROM python:3.10-slim

WORKDIR /app
COPY pyproject.toml .
RUN pip install poetry==1.7.1 && \
    poetry config virtualenvs.create false && \
    poetry install --only main --no-root
COPY . .
CMD ["uvicorn", "stemrunner.server:app", "--host", "0.0.0.0", "--port", "8000"]
